version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies and Packages
          command: |
            sudo apt update
            sudo apt install -y qt5-default
            python3 -m venv venv
            . venv/bin/activate
            pip install .[dev] codecov
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            mkdir test-repoorts
            set -x
            xvfb-run pytest \
              --strict \
              --cov=bci_learning_studio \
              --junitxml=test-reports/junit.xml \
              tests
            sed -i "s|venv/lib/python3.6/site-packages||g" .coverage
            codecov
      - run:
          name: Style Check
          command: |
            . venv/bin/activate
            flake8 bci_learning_studio

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  test:
    jobs:
      - test
